### ISSUE TITLE
Doesn't build against libpng12-dev

### ISSUE THREAD

**Issue by joolswills** [loganmc10/GLupeN64#97]
glupen64 doesn't currently build against libpng12-dev  (due to missing png_set_longjmp_fn)

```
./GLideN64/src/GLideNHQ/TxImage.o: In function `TxImage::getPNGInfo(_IO_FILE*, png_struct_def**, png_info_def**)':
TxImage.cpp:(.text+0xb4): undefined reference to `png_set_longjmp_fn'
./GLideN64/src/GLideNHQ/TxImage.o: In function `TxImage::writePNG(unsigned char*, _IO_FILE*, int, int, int, unsigned short, unsigned char*)':
TxImage.cpp:(.text+0x434): undefined reference to `png_set_longjmp_fn'
collect2: error: ld returned 1 exit status
Makefile:298: recipe for target 'glupen64_libretro.so' failed
make: *** [glupen64_libretro.so] Error 1
Removing additional swap
/home/pi/RetroPie-Setup
Could not successfully build N64 emu - GLupeN64 for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-glupen64/glupen64_libretro.so not found).
```

Tested on on Ubuntu 16.04 x86_64 (`make`) and Raspbian Jessie on a RPI3 (`make platform=rpi3`)

I have git bisected the issue to 033df1521ea9f97e148c8497d01e3a9578d83710

```
commit 033df1521ea9f97e148c8497d01e3a9578d83710
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Mon Nov 7 13:20:12 2016 -0700

    Hi-Res Texture Support

:100644 100644 6e06052f88a7cdcec98754c5000e90abe0831b8f 56590cd517ffaa8cd0d9007921cd6b294a944828 M	.travis.yml
:100644 100644 91b32deff42acd85f095834e12de4a770153ee21 33cc7978d58034c9a3ecb66b283509f0fedae848 M	Makefile
:100644 100644 e62b4b82c752cd70518516e23da0e6479242e5d9 38481102c54676061c44f0e5253c00baf973a7a7 M	Makefile.common
:040000 040000 d34064822976c012d70833ff7a295cb8d89e2f92 47dd6b94f1192053a02d5651dece864e75888ce1 M	custom
:040000 040000 7562312dd1d4f4919e9d22b8a2394dc63de1e5fd 1a76bddc7d1d9664a57156eb45f6fa08c5703465 M	libretro
```

see https://github.com/RetroPie/RetroPie-Setup/issues/1741

also to confirm bison/flex is now a dependency ?

**Comment by joolswills** [comment]
Ubuntu 16.04 does have a libpng16-dev, but that conflicts with libpng12-dev which is required by libfreetype6-dev which breaks other stuff (ubuntu packaging problem). Also libpng16 is not available on Raspbian Jessie, so I assume it should be buildable against the older png ?

**Comment by loganmc10** [comment]
Yes should be fixed by 741ac99de8db1f7cc5d51d4975735c6f1c6e948a

It was including a version of png.h that assumed support for that feature, this should use the system's png.h

**Comment by joolswills** [comment]
Confirmed working. Thanks :)

**Comment by loganmc10** [comment]
Sorry I realised I didn't answer your other question.

Yes, flex and bison are build requirements for GLupeN64, but only for GLES devices, full OpenGL devices don't need them.
